---
- hosts: all
  become: true
  pre_tasks:

   - name: update repo chache (Ubuntu)
     tags: always
     apt:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Ubuntu"



   - name: update repo chache (Centos)
     tags: always
     dnf:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "CentOS"

- hosts: group1
  become: true
  tasks:


   - name: install apache and php for Ubuntu servers
     tags: grp
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"
   - name: install apache and php for CentOS servers
     tags: grp
     dnf:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "CentOS"

   - name: start httpd
     tags: grp,httpd
     service:
       name: httpd
       state: started
       enabled: yes
     when: ansible_distribution == "CentOS"


   - name: change e-mail address for admin
     tags: grp,httpd
     lineinfile: 
       path: /etc/httpd/conf/httpd.conf
       regexp: '^ServerAdminb'
       line: ServerAdmin somebody@somewhere.net
     when: ansible_distribution == "CentOS"
     register: httpd


   - name: restart httpd (Centos)
     tags: grp,httpd
     service:
       name: httpd
       state: restarted
     when: httpd.changed

   - name: Copy fichier html depuis le controller vers webservers
     tags: grp
     copy:
       src: default_install_apache_targetinghost.html 
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644




- hosts: all
  become: true
  tasks:


  - name: add ssh key for ali
    tags: always
    authorized_key:
      user: ali
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBm6+m0WvdN3s+Cy95TwsrjmKO2JXwFa8TeU0jYOwGN8 ansible-lab-key"


- hosts: workstations
  become: true
  tasks:

    - name: install unzip
      package: 
        name: unzip

    - name: install terraform
      unarchive:
         src: https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
         dest: /usr/local/bin
         remote_src: yes
         mode: 0755
         owner: root
         group: root
