---

- hosts: all
  become: true
  tasks: 

  - name: remove apache2 package
    dnf:
      name: httpd
      state: absent
      

  - name: "remove  php support for apache"
    dnf:
      name: php
      state: absent


